package pl.ndt.manager.model.enums;

public enum Sectors {
	CASTINGS, FORGINGS, WELDED_PRODUCTS, TUBES, WROUGHT, METAL_MANUFACTURING, PRE_AND_IN_SERVICE, RAILWAY, AREOSPACE, METL_PRE_AND_IN_SERVICE
}
